blog/urls.py
from django.urls import path
from . import views

# app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', views.blog, name="blog"),
    path('blog/ourgiftcard/toyou/cyprine', views.card, name="card"),
    path('about/', views.about, name="about"),
    path('resources/', views.resources, name="resources"),
    path('contact/', views.contactus, name="contact"),
    # path('shop/', views.shop, name="shop"),
    path('blog/<str:article_title>', views.blogArticles, name="blog_articles"),
    path('comment/<str:comment>', views.blogComment, name="comments"),
    path('podcast/', views.podcast, name="podcast"),
    path('subscribe/', views.subscribe, name="subscribe"),
    path('process_subscriber/', views.processSubscriber, name="process_subscriber"),
    path('process_contact/', views.processContact, name="process_contact"),

    path('blog/category/<str:category_name>', views.blogCategorypage, name="blog_category_page"),

]

julio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('shop/', include('store.urls')),
    path('signup/', include('users.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.index, name="shop_home"),
    path('', views.store, name="store"),
    path('store/nike/', views.nike, name="site-nike"),
    path('store/adidas/', views.adidas, name="site-adidas"),
    path('store/balenciaga/', views.balenciaga, name="site-balenciaga"),
    path('store/category/', views.dior, name="site-dior"),
    path('store/search/', views.search, name="searches"),


    
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.updateItem, name="update_item"),
    path('cart/update_item/', views.updateItem, name="update_item"),
    path('checkout/process_order/', views.processOrder, name="process_order"),
    path('processContact/', views.processContact, name="processContact"),
]

users/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('', views.register, name="site-reg"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name="site-profile"),
    path('changePassword', views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name="site-login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name="site-logout"),
]

store/models.py
from email import message
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
    user = models.CharField(max_length=200, null=True)#models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)
    
    def __str__(self):
        return str(self.user)
    

class Featuredproduct(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='products/')
    
    @property
    def imageURL(self):
        try:
            url =self.image.url
        except:
            url = ''
        return url
    
    
    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return str(self.id)
    
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum(item.get_total for item in orderitems)
        return total
        
    
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
    
class OrderItem(models.Model):   
    product = models.ForeignKey(Featuredproduct, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
        


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False, default="hometown_admin")
    phone = models.CharField(max_length=200, null=False, default="admin") 
    state = models.CharField(max_length=200, null=False, default="admin")
    zipcode = models.CharField(max_length=200, null=False, default="admin")
    mpesacode = models.CharField(max_length=10, null=False, default="admin")
    date_added = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return str(self.customer)


class Contact(models.Model):
    name = models.CharField(max_length=200, null=False)
    email = models.CharField(max_length=200, null=False) 
    message = models.CharField(max_length=200, null=False)
    subject = models.CharField(max_length=200, null=False)
    
    
    
    def __str__(self):
        return self.email
    
    
    
    
    
    
    

store/views.py
import email
from email import message
from itertools import product
from unicodedata import name
from django.shortcuts import render
from django.db.models import Q
from .models import *
from django.http import JsonResponse
import json
import datetime
from django.contrib.auth.models import User
from .utils import cookieCart, cartData, productDet, guestOrder
#import requests
#from request.auth import HTTPBasicAuth


# Create your views here.
def index(request):
    
    context = {}
    return render(request, 'store/index.html', context)
    

def about(request):
    
    
    context = { 'title':'about',}
    return render(request, 'store/about.html', context)


def contact(request):
   
    context = {'title':'contactus',}
    return render(request, 'store/contacts.html', context)


def nike(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Featuredproduct.objects.all()
    
    context = {'products':products, 'cartItems':cartItems,'title':'nike',}
    return render(request, 'store/nike.html', context)

def adidas(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Featuredproduct.objects.all()
    
    context = {'products':products, 'cartItems':cartItems,'title':'adidas',}
    return render(request, 'store/adidas.html', context)

def balenciaga(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Featuredproduct.objects.all()
    
    context = {'products':products, 'cartItems':cartItems,'title':'balenciaga',}
    return render(request, 'store/balenciaga.html', context)


def dior(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Featuredproduct.objects.all()
    
    context = {'products':products, 'cartItems':cartItems,'title':'dior',}
    
  
    return render(request, 'store/dior.html', context)



def search(request):

    products = Featuredproduct.objects.all()
    query = request.GET.get("query")
    products_search = ""

    if query:
        products_search = products.filter(Q(name__icontains=query) | Q(description__icontains=query) )

    
    context = {
        'products_search': products_search,
        }
    return render(request, 'store/searches.html', context)

def store(request):
    
    data = cartData(request)
    cartItems = data['cartItems']
        
    products = Featuredproduct.objects.all()
    product_db = productDet(request,products)

    query = request.GET.get("query")

    products_search = ""

    if query:
        products_search = products.filter(Q(name__icontains=query) | Q(description__icontains=query) )

    
    context = {
        'products':products,
        "each_product_db":product_db['each_product_db'],
        'search_db':product_db['search_db'], 
        'cartItems':cartItems,
        'title':'store',
        'products_search': products_search,
        }
    return render(request, 'store/store2.html', context)

def cart(request):
    
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items':items, 'order':order, 'cartItems':cartItems,'title':'cart',}
    return render(request, 'store/cart.html', context)

def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items':items, 'order':order, 'cartItems':cartItems,'title':'checkout',}
    return render(request, 'store/checkout.html', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('action:', action)
    print('product:', productId)
    
    
    user = request.user.username
    customer = Customer.objects.get(user=user)
    product = Featuredproduct.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()
    
    
    return JsonResponse('item added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    
    if request.user.is_authenticated:
        #customer = request.user.customer
        user = request.user.username
        customer = Customer.objects.get(user=user)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        
        
        

    else:
        customer, order = guestOrder(request,data)
        

    total = float(data['shipping']['total'])
    order.transaction_id = transaction_id
    
    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    ShippingAddress.objects.create(
    customer=customer,
    order=order,
    address=data['shipping']['address'],
    phone=data['shipping']['phone'],
    state=data['shipping']['address'],
    zipcode=data['shipping']['postalcode'],
    mpesacode=data['userPayData']['payphone'],
    
    )


    return JsonResponse('payment complete', safe=False)


def processContact(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    

    Contact.objects.create(
    name=data['contactInfo']['name'],
    email=data['contactInfo']['email'],
    message=data['contactInfo']['message'],
    subject=data['contactInfo']['subject'],
    
    )


    return JsonResponse('contact sent', safe=False)

store/templates/store/adidas.html
{% extends 'store/base.html' %}
{% load static %}



{% block content %}
   
  
    {% include 'store/base.html %}
    
    <div class="labels-wrapper-box">
        
        <div class="store-child-1">
           
           <ul>
               <li style="padding-bottom: 9px; font-size: 20px;">
                   ADIDAS
               </li>
               <ul class="store-categories">
                   <li style="padding-bottom: 9px;"><a href="#">Yeezy</a></li>
                   <li style="padding-bottom: 9px;"><a href="#">Rafsimons</a></li>
                   
                   
               </ul>
           </ul>
            
        </div>
        
        <div style="position: relative;" class="store-child-2">
            
            {% for product in products %}
                
                {% if "adidas" in product.name %}
                
                <div class="prod-card">
                    <div class="product-top">
                        <img src="{{product.imageURL}}" alt="">
                        <div class="prod-overlay">
                            <button type="button" class="btn btn-secondary" title="Quick Shop">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </button>
                            <button type="button" class="btn btn-secondary" title=" Add to wishlist">
                                <i class="fa fa-heart" aria-hidden="true"></i>
                            </button>
                            <button data-product={{product.id}} data-action="add" class="btn update-cart btn-secondary" type="button" title="Add to cart">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                    <div class="product-bottom text-center">
                        <div>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </div>
                        
                        <h3>{{ product.name }}</h3>
                        <h5>{{ product.price|floatformat:2 }}</h5>
                    </div>
                    
                </div>
                 {% endif %}
         {% endfor %}
         
            
        </div>
        
        
        
        
    </div>
   
     
     
{% endblock %}

store/templates/store/balenciaga.html
{% extends 'store/base.html' %}
{% load static %}



{% block content %}
   
   
   
    
    <div class="labels-wrapper-box">
        
        <div class="store-child-1">
           
           <ul>
               <li style="padding-bottom: 9px; font-size: 20px;">
                   BALENCIAGA
               </li>
               <ul class="store-categories">
                   <li style="padding-bottom: 9px;"><a href="#">Track</a></li>
                   <li style="padding-bottom: 9px;"><a href="#">TripleS</a></li>
                   
                   
               </ul>
           </ul>
            
        </div>
        
        <div style="position: relative;" class="store-child-2">
            
            {% for product in products %}
                
                {% if "balenciaga" in product.name %}
                
                <div class="prod-card">
                    <div class="product-top">
                        <img src="{{product.imageURL}}" alt="">
                        <div class="prod-overlay">
                            <button type="button" class="btn btn-secondary" title="Quick Shop">
                                <i class="fa fa-eye" aria-hidden="true"></i></button>
                            <button type="button" class="btn btn-secondary" title=" Add to wishlist">
                                <i class="fa fa-heart" aria-hidden="true"></i></button>
                            <button data-product={{product.id}} data-action="add" class="btn update-cart btn-secondary" type="button" title="Add to cart">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                        </div>
                    </div>
                    <div class="product-bottom text-center">
                        <div>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </div>
                        
                        <h3>{{ product.name }}</h3>
                        <h5>{{ product.price|floatformat:2 }}</h5>
                    </div>
                    
                </div>
                 {% endif %}
         {% endfor %}
         
            
        </div>
        
        
        
        
    </div>
   
     
     
{% endblock %}

store/templates/store/base.html
{% extends 'blog/main.html' %}
{% load static %}



{% block content %}
  
        <header class="header">

            <div class="utility-nav d-none d-md-block">
                <div class="container">
                  <div class="row">
                    <div class="col-12 col-md-6">
                      <p class="small"><i class="fa fa-envelope"></i> kingsdaughter@gmail.com | <i class="fa fa-phone"></i> +254 7123456789
                      </p>
                    </div>
              
                    <div class="col-12 col-md-6 text-right">
                      <p class="small">Free shipping on total of $55 of all products</p>
                    </div>
                  </div>
                </div>
              </div>
              
              <nav class="navbar navbar-expand-md navbar-dark bg-dark main-menu" style="box-shadow:none">
                <div class="container">
              
                  
                  <a class="navbar-brand" href="{% url 'store' %}">
                    <img style="width: 50px; height: 50px; border-radius: 10px;" src="{% static 'img/images/logo3.png' %}" alt="">
                  </a>
              
                  <ul class="navbar-nav ml-auto d-block d-md-none">
                    <li class="nav-item">
                      <a class="btn " href="{% url 'cart' %}"><i class="fa fa-shopping-cart" style="color: white;"></i> <span class="badge badge-danger">{{cartItems}}</span></a>
                    </li>
                  </ul>
              
                  <div class="collapse navbar-collapse">
                    <form class="form-inline my-2 my-lg-0 mx-auto" method="get" action=".">
                      <input id="search-box" name="query" class="form-control" type="search" placeholder="Search for products..." aria-label="Search">
                      <a href="{% url 'searches' %}" id="search-btn" class="btn btn-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></a>
                    </form>
                   
              
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="btn " href="{% url 'cart' %}"><i class="fa fa-shopping-cart" style="color: white;"></i> <span class="badge badge-danger">{{cartItems}}</span></a>
                      </li>

                      {% if user.is_authenticated %}
                      <li class="nav-item ml-md-3">
                        <a class="btn btn-primary bg-dark" href="{% url 'users:site-logout' %}"><i class="fa fa-user-circle mr-1"></i> Logout</a>
                      </li>
                      {% else %}
                      <li class="nav-item ml-md-3">
                        <a class="btn btn-primary bg-dark" href="{% url 'users:site-reg' %}"><i class="fa fa-user-circle mr-1"></i> Log In / Register</a>
                      </li>
                      {% endif %}
                    </ul>
                  </div>
              
                </div>
              </nav>
              
              
              
              <div class="search-bar d-block d-md-none">
                <div class="container">
                  <div class="row">
                    <div class="col-12">
                      <form class="form-inline m-3 mx-auto">
                        <input class="form-control" type="search" placeholder="Search for products..." aria-label="Search">
                        <button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              
              <!-- Sidebar -->
              <nav id="sidebar">
                <div class="sidebar-header">
                  <div class="container">
                    <div class="row align-items-center">
                      <div class="col-10 pl-0">
                        {% if user.is_authenticated %}
                            <a class="btn btn-primary bg-dark" href="{% url 'users:site-logout' %}"><i class="fa fa-user-circle mr-1"></i> Log out</a>
                        {% else %}
                            <a class="btn btn-primary bg-dark" href="{% url 'users:site-login' %}"><i class="fa fa-user-circle mr-1"></i> Log In</a>
                        {% endif %}
                        
                      </div>
              
                      <div class="col-2 text-left">
                        <button type="button" id="sidebarCollapseX" class="btn ">
                            <i class="far fa-window-close"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              
                
              
                <h6 class="text-uppercase mb-1">Categories</h6>
                <ul class="list-unstyled components mb-3">
                  <li>
                    <a href="{% url 'site-nike' %}">Nike</a>
                  </li>
                  <li>
                    <a href="{% url 'site-adidas' %}">Addidas</a>
                  </li>
                  <li>
                    <a href="{% url 'site-dior' %}">Dior</a>
                  </li>
                  <li>
                    <a href="{% url 'site-balenciaga' %}">Balenciaga</a>
                  </li>
                  
                </ul>
              
                <ul class="social-icons">
                  <li><a href="#" target="_blank" title=""><i class="fa fa-facebook-square"></i></a></li>
                  <li><a href="#" target="_blank" title=""><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#" target="_blank" title=""><i class="fa fa-linkedin"></i></a></li>
                  <li><a href="#" target="_blank" title=""><i class="fa fa-instagram"></i></a></li>
                </ul>
              
              </nav>
      </header>
    
{% endblock %}

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<main class="main cart-items">
    <div class="container cart-page">
        <table class="cart_table">
            <!-- <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Subtotal</th>

            </tr> -->
            
                {% for item in items %}

                <tr>

                    <td>

                        <div class="cart-info">
                            <img src="{{ item.product.imageURL }}" alt="">
                            <div>
                                <p>
                                    {{ item.product.name|capfirst }}
                                </p>
                                <small>
                                    Price:Ksh {{item.product.price}}
                                </small>
                                <br>
                                <div class="q_btns">
                                    <a data-product="{{item.product.id}}" data-action="add" class="update-cart add_q">Add</a>
                                    <a data-product="{{item.product.id}}" data-action="remove" class="update-cart remove_q">Remove</a>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td><input type="text" value="{{item.quantity}}" disabled></td>
                    <td> Ksh {{ item.get_total }}</td>
                </tr>
                {% endfor %}
    

            

        </table>

        <div class="total-price">

            <table class="total_checkout">
                <tr>
                    <td colspan="2" style="padding-bottom: 20px; border-bottom: 0.5px rgb(77, 76, 76) dashed; width: 100%;">TOTAL</td>
                    
                </tr>
                <tr>
                    <td>Subtotal</td>
                    <td>Ksh {{ order.get_cart_total | floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>0.00</td>
                </tr>
                <tr>
                    <td>Items</td>
                    <td>{{ order.get_cart_items }}</td>
                </tr>
            </table>
        </div>
        
        <div class="cart_bottom">
            <!-- cart btns.......... -->
            <div class="cart_content_nav">
                
                <a href="{% url 'store' %}" class="btn btn-white" style="justify-self: flex-start; color: white; background-color: rgba(0, 0, 0, .25);">
                    <i class="fa fa-arrow-left" style="padding-right: 3px;"></i> Continue shopping
                </a>
                <a href="{% url 'checkout' %}" class="btn btn-primary pull-right" style="background-color: #075907b0; border: none;">
                    <i class="fa fa fa-shopping-cart"></i> Checkout
                </a>

            </div>

            
        </div>

    </div>

</main>
{% endblock %}

store/templates/store/contacts.html
{% extends 'store/base.html' %}
{% load static %}



{% block content %}
    
     <!--Section: Contact v.2-->
<section class="mb-4" style="width: 85%; margin: auto; color: white; display: grid; place-items: center;">

  <!--Section heading-->
  <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
  <!--Section description-->
  <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. <br/> team will come back to you within
      a matter of hours to help you.</p>

  <div class="row">

      <!--Grid column-->
      <div class="col-md-9 mb-md-0 mb-5">
          <form id="form" name="contact-form">

              <!--Grid row-->
              <div class="row">

                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                          <input type="text" id="name" name="name" class="form-control">
                          <label for="name" class="">Your name</label>
                      </div>
                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-md-6">
                      <div class="md-form mb-0">
                          <input type="text" id="email" name="email" class="form-control">
                          <label for="email" class="">Your email</label>
                      </div>
                  </div>
                  <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row">
                  <div class="col-md-12">
                      <div class="md-form mb-0">
                          <input type="text" id="subject" name="subject" class="form-control">
                          <label for="subject" class="">Subject</label>
                      </div>
                  </div>
              </div>
              <!--Grid row-->

              <!--Grid row-->
              <div class="row">

                  <!--Grid column-->
                  <div class="col-md-12">

                      <div class="md-form">
                          <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                          <label for="message">Your message</label>
                      </div>

                  </div>
              </div>
              <!--Grid row-->
              <div class="text-center text-md-left">
                <a class="btn btn-primary" id="send-form" type="submit">Send</a>
               </div>

          </form>

          
          <div class="status"></div>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-3 text-center">
          <ul class="list-unstyled mb-0">
              <li><i class="fas fa-map-marker-alt fa-2x"></i>
                  <p>Nairobi, Kenya, Africa</p>
              </li>

              <li><i class="fas fa-phone mt-4 fa-2x"></i>
                  <p>+254 7123456789</p>
              </li>

              <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                  <p>Ecom201@gmail.com</p>
              </li>
          </ul>
      </div>
      <!--Grid column-->

  </div>

</section>

<script>
    var form = document.getElementById('form');
    document.getElementById('send-form').addEventListener('click', function(){ 
        submitFormData()       
    })    

    function submitFormData(){
        
        var contactInfo = {
            'name': form.name.value,
            'email': form.email.value,
            'subject': form.subject.value,
            'message': form.message.value,
            
        }
        
        
        var url = '/processContact/';

                fetch(url, {
                    method:'POST',
                    headers: {
                        'Content-Type':'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body:JSON.stringify({'contactInfo': contactInfo,})

                })
                .then(response => response.json())
                .then(data => {
                    console.log('success:',data);
                    alert('contact sent');
                    // deleting the cart cookie on complete transaction
                    cart = {}
                    document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/";

                    window.location.href = "{% url 'store' %}"
                })
        
        
    }
</script>
<!--Section: Contact v.2-->
{% endblock %}

store/templates/store/dior.html
{% extends 'blog/main.html' %}
{% load static %}


{% block content %}

<section class="coming_soon">

</section>

{% endblock %}